baseURL: "https://www.simple-crypto.org/"
theme: "up-business-theme"
languageCode: "en-us"

title: "SIMPLE Crypto"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "SIMPLE Crypto"
  description: ""
  title_footer: false
  images:
    - "images/hero-image.png"

      #  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  location:
    - "
      SIMPLE-Crypto ASBL<br>
      Place du Levant 3 bte L5.03.02<br>
      1348 Louvain-la-Neuve<br>
      Belgium
      "

  contact:
    - '<a href="mailto:info@simple-crypto.org">info@simple-crypto.org</a>'

  copyright: '© 2023 SIMPLE Crypto (<a href="https://gitlab.com/writeonlyhugo/up-business-demo">webiste template</a>)'

  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "About"
      url: "/about"
      weight: 2

    - name: "Activities"
      url: "/activities"
      weight: 3

    - name: "People"
      url: "/people"
      weight: 4

    - name: "Sponsors"
      url: "/sponsors"
      weight: 5

    - name: "Contributing"
      url: "/contributing"
      weight: 6

  buttons:
    - name: "Fork us on Github"
      url: "https://github.com/simple-crypto"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/company/simple-crypto-association/"
      weight: 1

#module:
#  mounts:
#    - source: themes/up-business-theme/assets
#      target: assets

markup:
  goldmark:
    renderer:
      unsafe: true
